title: Brandon's 
theme: minima
author: Brandon
email: myfriendkang@gamil.com
description: > # this means to ignore newlines until "baseurl:"
 testing 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
